{{- /* Immutable v1.35 furyctl.yaml, rendered from drydock answers. Questions live in immutable-v1.35.yaml. */ -}}
{{- $t := .topology -}}
{{- $k := .kubernetes -}}
{{- $m := .modules -}}
{{- $cps := list }}{{ $etcds := list }}{{ $lbs := list }}{{ $infra := list }}{{ $workers := list }}
{{- range .nodes }}
  {{- if eq .role "cp" }}{{ $cps = append $cps . }}{{ end }}
  {{- if eq .role "etcd" }}{{ $etcds = append $etcds . }}{{ end }}
  {{- if eq .role "lb" }}{{ $lbs = append $lbs . }}{{ end }}
  {{- if eq .role "infra" }}{{ $infra = append $infra . }}{{ end }}
  {{- if eq .role "workers" }}{{ $workers = append $workers . }}{{ end }}
{{- end }}
{{- $proxy := dig "cluster" "proxy" (dict) . -}}
# yaml-language-server: $schema=https://raw.githubusercontent.com/sighupio/distribution/{{ .version }}/schemas/public/immutable-kfd-v1alpha2.json
# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
# Generated by `furyctl drydock`. Review it, export the referenced environment variables,
# prepare the referenced files, then run `furyctl validate config` and `furyctl apply`.
# Reference: https://docs.sighup.io/docs/installation/sd-configuration/providers/Immutable
---
apiVersion: kfd.sighup.io/v1alpha2
kind: Immutable
metadata:
  name: {{ .cluster.name | quote }}
spec:
  distributionVersion: {{ .version }}

  infrastructure:
    # SSH access to the nodes after the first boot.
    ssh:
      username: {{ .cluster.sshUser | quote }}
      privateKeyPath: {{ .cluster.sshPrivateKey | quote }}
{{- with dig "cluster" "sshPublicKey" "" . }}
      publicKeyPath: {{ . | quote }}
{{- end }}

    # furyctl serves the boot assets from this URL during `furyctl apply`.
    ipxeServer:
      url: {{ .cluster.ipxeUrl | quote }}
{{- with dig "cluster" "ipxeBindAddress" "" . }}
      bindAddress: {{ . | quote }}
{{- end }}
{{- with dig "cluster" "ipxeBindPort" "" . }}
      bindPort: {{ . }}
{{- end }}
{{- if or $proxy.http $proxy.https }}

    proxy:
{{- with $proxy.http }}
      http: {{ . | quote }}
{{- end }}
{{- with $proxy.https }}
      https: {{ . | quote }}
{{- end }}
{{- with $proxy.noProxy }}
      noProxy: {{ . | quote }}
{{- end }}
{{- end }}

    # One entry per machine. Roles are assigned below in kubernetes.controlPlane, etcd,
    # nodeGroups and infrastructure.loadBalancers by hostname.
    nodes:
{{- range .nodes }}
{{- $adv := dig "advanced" (dict) . }}
      - hostname: {{ .hostname | quote }}
        macAddress: {{ .macAddress | quote }}
{{- if ne (default "x86-64" .arch) "x86-64" }}
        arch: {{ .arch }}
{{- end }}
        storage:
          installDisk: {{ .installDisk | quote }}
{{- with $adv.disks }}
          disks:
{{- range . }}
            - device: {{ .device | quote }}
              wipe_table: {{ .wipeTable }}
{{- with .partitions }}
              partitions:
{{- range . }}
                - label: {{ .label | quote }}
{{- with .number }}
                  number: {{ . }}
{{- end }}
{{- with .sizeMib }}
                  size_mib: {{ . }}
{{- end }}
{{- with .startMib }}
                  start_mib: {{ . }}
{{- end }}
{{- with .typeGuid }}
                  type_guid: {{ . | quote }}
{{- end }}
                  should_exist: {{ .shouldExist }}
                  resize: {{ .resize }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- with $adv.filesystems }}
          filesystems:
{{- range . }}
            - device: {{ .device | quote }}
              format: {{ .format }}
{{- with .path }}
              path: {{ . | quote }}
{{- end }}
{{- with .label }}
              label: {{ . | quote }}
{{- end }}
              wipe_filesystem: {{ .wipeFilesystem }}
              with_mount_unit: {{ .withMountUnit }}
{{- with .options }}
              options:
{{- range . }}
                - {{ . | quote }}
{{- end }}
{{- end }}
{{- with .mountOptions }}
              mount_options:
{{- range . }}
                - {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- with $adv.directories }}
          directories:
{{- range . }}
            - path: {{ .path | quote }}
              mode: {{ .mode }}
              overwrite: {{ .overwrite }}
{{- with .user }}
              user:
                name: {{ . | quote }}
{{- end }}
{{- with .group }}
              group:
                name: {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- with $adv.files }}
          files:
{{- range . }}
            - path: {{ .path | quote }}
              mode: {{ .mode }}
              overwrite: {{ .overwrite }}
{{- with .contents }}
              contents:
                inline: |-
{{ . | indent 18 }}
{{- end }}
{{- with .user }}
              user:
                name: {{ . | quote }}
{{- end }}
{{- with .group }}
              group:
                name: {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- with $adv.links }}
          links:
{{- range . }}
            - path: {{ .path | quote }}
              target: {{ .target | quote }}
              hard: {{ .hard }}
{{- end }}
{{- end }}
        network:
          ethernets:
            {{ .interface | quote }}:
{{- if eq .networkMode "dhcp" }}
              dhcp4: true
{{- else }}
              addresses:
{{- /* A blank IP stays blank, so the schema reports "still to fill" and not a broken "/24". */}}
                - {{ if .ip }}{{ printf "%s/%v" .ip .prefixLength | quote }}{{ else }}""{{ end }}
              gateway: {{ .gateway | quote }}
{{- if or .nameservers .searchDomains }}
              nameservers:
{{- with .nameservers }}
                addresses:
{{- range . }}
                  - {{ . | quote }}
{{- end }}
{{- end }}
{{- with .searchDomains }}
                search:
{{- range . }}
                  - {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- with .routes }}
              routes:
{{- range . }}
                - to: {{ .to | quote }}
                  via: {{ .via | quote }}
{{- end }}
{{- end }}
{{- with $adv.systemdUnits }}
        systemd:
          units:
{{- range . }}
            - name: {{ .name | quote }}
              enabled: {{ .enabled }}
{{- if .mask }}
              mask: true
{{- end }}
{{- with .contents }}
              contents: |-
{{ . | indent 16 }}
{{- end }}
{{- with .dropins }}
              dropins:
{{- range . }}
                - name: {{ .name | quote }}
{{- with .contents }}
                  contents: |-
{{ . | indent 20 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if or $adv.users $adv.groups }}
        passwd:
{{- with $adv.users }}
          users:
{{- range . }}
            - name: {{ .name | quote }}
{{- with .sshAuthorizedKeys }}
              ssh_authorized_keys:
{{- range . }}
                - {{ . | quote }}
{{- end }}
{{- end }}
{{- with .groups }}
              groups:
{{- range . }}
                - {{ . | quote }}
{{- end }}
{{- end }}
{{- with .shell }}
              shell: {{ . | quote }}
{{- end }}
{{- with .passwordHash }}
              password_hash: {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- with $adv.groups }}
          groups:
{{- range . }}
            - name: {{ .name | quote }}
{{- with .gid }}
              gid: {{ . }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if or $adv.kernelArgsAdd $adv.kernelArgsRemove }}
        kernelArguments:
{{- with $adv.kernelArgsAdd }}
          shouldExist:
{{- range . }}
            - {{ . | quote }}
{{- end }}
{{- end }}
{{- with $adv.kernelArgsRemove }}
          shouldNotExist:
{{- range . }}
            - {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- with $adv.kernelParameters }}
        kernelParameters:
{{- range . }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- if $lbs }}

    # HAProxy in front of the API server{{ if eq (len $lbs) 2 }}, with a keepalived floating IP{{ end }}.
    loadBalancers:
      members:
{{- range $lbs }}
        - hostname: {{ .hostname | quote }}
{{- end }}
      keepalived:
{{- if eq (len $lbs) 2 }}
        enabled: true
        interface: {{ $t.vipInterface | quote }}
        ip: {{ $t.vip | quote }}
        virtualRouterId: {{ $t.virtualRouterId | toString | quote }}
{{- else }}
        enabled: false
{{- end }}
{{- end }}

  kubernetes:
{{- with dig "kubernetes" "version" "" . }}
    version: {{ . | quote }}
{{- end }}
    # Generate the CA files here with `furyctl create pki` before `furyctl apply`.
    pkiPath: {{ .cluster.pkiPath | quote }}
    networking:
      podCIDR: {{ $k.podCIDR | quote }}
      serviceCIDR: {{ $k.serviceCIDR | quote }}
    controlPlane:
      # Must resolve to the load balancer, the floating IP, or the first control plane node.
      address: {{ default (printf "api.%s:6443" .cluster.domain) (dig "topology" "controlPlaneAddress" "" .) | quote }}
      members:
{{- range $cps }}
        - hostname: {{ .hostname | quote }}
{{- end }}
{{- if $t.schedulableControlPlane }}
      # No dedicated workers: ordinary pods are scheduled on the control plane too.
      taints: []
{{- end }}
{{- if eq $t.lbMode "keepalived-on-cp" }}
      keepalived:
        enabled: true
        interface: {{ $t.vipInterface | quote }}
        ip: {{ $t.vip | quote }}
        virtualRouterId: {{ $t.virtualRouterId | toString | quote }}
{{- end }}
{{- if $etcds }}
    etcd:
      members:
{{- range $etcds }}
        - hostname: {{ .hostname | quote }}
{{- end }}
{{- end }}
{{- if not (or $infra $workers (dig "topology" "extraGroups" (list) .)) }}
    # Every machine is a control plane node: there are no worker groups.
    nodeGroups: []
{{- else }}
    nodeGroups:
{{- if $infra }}
      - name: infra
        labels:
          node-role.kubernetes.io/infra: ""
        taints:
          - key: node-role.kubernetes.io/infra
            value: ""
            effect: NoSchedule
        nodes:
{{- range $infra }}
          - hostname: {{ .hostname | quote }}
{{- end }}
{{- end }}
{{- if $workers }}
      - name: workers
        nodes:
{{- range $workers }}
          - hostname: {{ .hostname | quote }}
{{- end }}
{{- end }}
{{- range $g := dig "topology" "extraGroups" (list) . }}
      - name: {{ $g.name | quote }}
{{- with $g.labels }}
        labels:
{{- range $k, $v := . }}
          {{ $k | quote }}: {{ $v | quote }}
{{- end }}
{{- end }}
{{- with $g.taints }}
        taints:
{{- range . }}
          - key: {{ .key | quote }}
            value: {{ .value | quote }}
            effect: {{ .effect }}
{{- end }}
{{- end }}
        nodes:
{{- range $.nodes }}
{{- if and (eq .role "custom") (eq .group $g.name) }}
          - hostname: {{ .hostname | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- $kp := dig "kubernetes" "kubeProxy" "default" . }}
{{- $oidc := dig "kubernetes" "oidc" (dict) . }}
{{- $sr := dig "kubernetes" "systemReserved" (dict) . }}
{{- if or (ne $kp "default") $k.encryption $k.oidcEnabled $k.registry $k.certSANs $k.maxPods $sr.cpu $sr.memory $sr.ephemeralStorage }}
    advanced:
{{- if ne $kp "default" }}
      kubeProxy:
        type: {{ $kp }}
{{- end }}
{{- if $k.encryption }}
      encryption:
        configuration: {{ $k.encryptionConfig | quote }}
{{- end }}
{{- if $k.oidcEnabled }}
      oidc:
        issuer_url: {{ $oidc.issuerUrl | quote }}
        client_id: {{ $oidc.clientId | quote }}
{{- with $oidc.usernameClaim }}
        username_claim: {{ . | quote }}
{{- end }}
{{- with $oidc.groupsClaim }}
        groups_claim: {{ . | quote }}
{{- end }}
{{- with $oidc.caFile }}
        ca_file: {{ . | quote }}
{{- end }}
{{- end }}
{{- with $k.registry }}
      registry: {{ . | quote }}
{{- end }}
{{- with $k.certSANs }}
      apiServer:
        certSANs:
{{- range . }}
          - {{ . | quote }}
{{- end }}
{{- end }}
{{- if or $k.maxPods $sr.cpu $sr.memory $sr.ephemeralStorage }}
      kubeletConfiguration:
{{- with $k.maxPods }}
        maxPods: {{ . }}
{{- end }}
{{- if or $sr.cpu $sr.memory $sr.ephemeralStorage }}
        systemReserved:
{{- with $sr.cpu }}
          cpu: {{ . | quote }}
{{- end }}
{{- with $sr.memory }}
          memory: {{ . | quote }}
{{- end }}
{{- with $sr.ephemeralStorage }}
          ephemeral-storage: {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

  distribution:
{{- if $infra }}
    common:
      # The distribution's own workloads run on the infra nodes.
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists
          effect: NoSchedule
{{- end }}
    modules:
      networking:
        type: {{ $m.networking.type }}
{{- with $m.networking.nodeSubnetSize }}
{{- if eq $m.networking.type "calico" }}
        tigeraOperator:
          # One /{{ . }} of the pod CIDR per node.
          blockSize: {{ . }}
{{- else }}
        cilium:
          # One /{{ . }} of the pod CIDR per node.
          maskSize: {{ . | toString | quote }}
{{- end }}
{{- end }}
{{- $ing := $m.ingress }}

      ingress:
        baseDomain: {{ $ing.baseDomain | quote }}
{{- if eq $ing.controller "byoic" }}
        byoic:
          enabled: true
          ingressClass: {{ $ing.byoicIngressClass | quote }}
{{- else }}
        {{ $ing.controller }}:
          type: {{ $ing.type }}
{{- if and (ne $ing.type "none") $ing.tlsProvider }}
          tls:
            provider: {{ $ing.tlsProvider }}
{{- if eq $ing.tlsProvider "secret" }}
            secret:
              cert: {{ $ing.tlsCert | quote }}
              key: {{ $ing.tlsKey | quote }}
              ca: {{ $ing.tlsCa | quote }}
{{- end }}
{{- end }}
{{- end }}
        certManager:
          clusterIssuer:
            name: {{ $ing.issuerName | quote }}
            email: {{ $ing.issuerEmail | quote }}
{{- if eq $ing.issuerType "http01" }}
            type: http01
{{- else }}
            solvers:
{{ $ing.issuerSolvers | indent 14 }}
{{- end }}
{{- $log := $m.logging }}

      logging:
        type: {{ $log.type }}
{{- if eq $log.type "loki" }}
        loki:
          backend: {{ $log.lokiBackend }}
{{- if eq $log.lokiBackend "externalEndpoint" }}
          externalEndpoint:
            endpoint: {{ $log.lokiEndpoint | quote }}
            bucketName: {{ $log.lokiBucket | quote }}
            accessKeyId: {{ $log.lokiAccessKeyId | quote }}
            secretAccessKey: {{ $log.lokiSecretAccessKey | quote }}
            insecure: {{ $log.lokiInsecure }}
{{- end }}
{{- with $log.lokiRetention }}
          retentionTime: {{ . | quote }}
{{- end }}
{{- else if eq $log.type "opensearch" }}
        opensearch:
          type: {{ $log.opensearchType }}
{{- with $log.opensearchStorageSize }}
          storageSize: {{ . | quote }}
{{- end }}
{{- end }}
{{- $mon := $m.monitoring }}

      monitoring:
        type: {{ $mon.type }}
{{- if eq $mon.type "prometheus" }}
        prometheus:
{{- with $mon.retentionTime }}
          retentionTime: {{ . | quote }}
{{- end }}
{{- with $mon.retentionSize }}
          retentionSize: {{ . | quote }}
{{- end }}
{{- with $mon.storageSize }}
          storageSize: {{ . | quote }}
{{- end }}
{{- else if eq $mon.type "prometheusAgent" }}
        prometheusAgent:
          remoteWrite:
            - url: {{ $mon.remoteWriteUrl | quote }}
{{- else if eq $mon.type "mimir" }}
        mimir:
          backend: {{ $mon.mimirBackend }}
{{- if eq $mon.mimirBackend "externalEndpoint" }}
          externalEndpoint:
            endpoint: {{ $mon.mimirEndpoint | quote }}
            bucketName: {{ $mon.mimirBucket | quote }}
            accessKeyId: {{ $mon.mimirAccessKeyId | quote }}
            secretAccessKey: {{ $mon.mimirSecretAccessKey | quote }}
{{- end }}
{{- end }}
{{- with $mon.slackWebhookUrl }}
        alertmanager:
          slackWebhookUrl: {{ . | quote }}
{{- end }}
{{- $tr := $m.tracing }}

      tracing:
        type: {{ $tr.type }}
{{- if eq $tr.type "tempo" }}
        tempo:
          backend: {{ $tr.tempoBackend }}
{{- if eq $tr.tempoBackend "externalEndpoint" }}
          externalEndpoint:
            endpoint: {{ $tr.tempoEndpoint | quote }}
            bucketName: {{ $tr.tempoBucket | quote }}
            accessKeyId: {{ $tr.tempoAccessKeyId | quote }}
            secretAccessKey: {{ $tr.tempoSecretAccessKey | quote }}
{{- end }}
{{- end }}
{{- $pol := $m.policy }}

      policy:
        type: {{ $pol.type }}
{{- if eq $pol.type "gatekeeper" }}
        gatekeeper:
          enforcementAction: {{ $pol.gatekeeperAction }}
          installDefaultPolicies: true
{{- else if eq $pol.type "kyverno" }}
        kyverno:
          validationFailureAction: {{ $pol.kyvernoAction }}
          installDefaultPolicies: true
{{- end }}
{{- $dr := $m.dr }}

      dr:
        type: {{ $dr.type }}
{{- if eq $dr.type "on-premises" }}
        velero:
          backend: {{ $dr.veleroBackend }}
{{- if eq $dr.veleroBackend "externalEndpoint" }}
          externalEndpoint:
            endpoint: {{ $dr.veleroEndpoint | quote }}
            bucketName: {{ $dr.veleroBucket | quote }}
            accessKeyId: {{ $dr.veleroAccessKeyId | quote }}
            secretAccessKey: {{ $dr.veleroSecretAccessKey | quote }}
{{- end }}
{{- $eb := default "none" $dr.etcdBackupType }}
{{- if ne $eb "none" }}
        etcdBackup:
          type: {{ $eb }}
{{- if or (eq $eb "pvc") (eq $eb "all") }}
          pvc:
            schedule: {{ $dr.etcdBackupSchedule | quote }}
            retentionTime: {{ $dr.etcdBackupRetention | quote }}
{{- with $dr.etcdPvcSize }}
            size: {{ . | quote }}
{{- end }}
{{- with $dr.etcdPvcStorageClass }}
            storageClass: {{ . | quote }}
{{- end }}
{{- end }}
{{- if or (eq $eb "s3") (eq $eb "all") }}
          s3:
            schedule: {{ $dr.etcdBackupSchedule | quote }}
            retentionTime: {{ $dr.etcdBackupRetention | quote }}
            endpoint: {{ $dr.etcdS3Endpoint | quote }}
            bucketName: {{ $dr.etcdS3Bucket | quote }}
            accessKeyId: {{ $dr.etcdS3AccessKeyId | quote }}
            secretAccessKey: {{ $dr.etcdS3SecretAccessKey | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- $auth := $m.auth }}

      auth:
        provider:
          type: {{ $auth.provider }}
{{- if eq $auth.provider "basicAuth" }}
          basicAuth:
            username: {{ $auth.basicUsername | quote }}
            password: {{ $auth.basicPassword | quote }}
{{- else if eq $auth.provider "sso" }}
        baseDomain: {{ default $ing.baseDomain $auth.baseDomain | quote }}
        dex:
          connectors:
{{- if $auth.dexConnectors }}
{{ $auth.dexConnectors | indent 12 }}
{{- else }}
            # PLACEHOLDER: replace with your identity provider. Dex connector reference:
            # https://dexidp.io/docs/connectors/
            - type: github
              id: github
              name: GitHub
              config:
                clientID: "{env://DEX_GITHUB_CLIENT_ID}"
                clientSecret: "{env://DEX_GITHUB_CLIENT_SECRET}"
                redirectURI: https://login.{{ default $ing.baseDomain $auth.baseDomain }}/callback
{{- end }}
{{- end }}
