// Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package mise

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// configFilePerm is the permission of the generated mise.toml (a config file, not a secret).
const configFilePerm = 0o644

// Tool describes how a furyctl tool maps to mise.
type Tool struct {
	// Spec is the mise.toml [tools] key (registry shortname or explicit backend).
	Spec string
	// Bin is the executable name, used both for `mise which` and as the materialized symlink name.
	// It is what phase.go / the runners expect under <binPath>/<furyctlName>/<version>/<Bin>.
	Bin string
}

// ManagedTools maps the furyctl tool name (lowercased kfd field) to its mise mapping. Only these are
// managed by mise; awscli/ansible/git stay host dependencies; terraform is kept for backward
// compatibility with distributions that predate opentofu.
//
//nolint:gochecknoglobals // static mapping table.
var ManagedTools = map[string]Tool{
	"kubectl":   {Spec: "kubectl", Bin: "kubectl"},
	"kustomize": {Spec: "kustomize", Bin: "kustomize"},
	"yq":        {Spec: "yq", Bin: "yq"},
	"helm":      {Spec: "helm", Bin: "helm"},
	"helmfile":  {Spec: "helmfile", Bin: "helmfile"},
	"kapp":      {Spec: "kapp", Bin: "kapp"},
	"opentofu":  {Spec: "opentofu", Bin: "tofu"},
	"terraform": {Spec: "aqua:hashicorp/terraform", Bin: "terraform"},
	"furyagent": {Spec: "ubi:sighupio/furyagent", Bin: "furyagent"},
}

// IsManaged reports whether the given furyctl tool is managed by mise.
func IsManaged(name string) bool {
	_, ok := ManagedTools[name]

	return ok
}

// WriteConfig writes a hermetic mise.toml at path with a [tools] section for the given tools
// (furyctl tool name -> version). Keys are always quoted (backends contain ':' and '/').
func WriteConfig(path string, tools map[string]string) error {
	names := make([]string, 0, len(tools))
	for n := range tools {
		names = append(names, n)
	}

	sort.Strings(names)

	lines := []string{"# Generated by furyctl. Do not edit.", "[tools]"}

	for _, n := range names {
		t, ok := ManagedTools[n]
		if !ok {
			continue
		}

		lines = append(lines, fmt.Sprintf("%q = %q", t.Spec, tools[n]))
	}

	content := strings.Join(lines, "\n") + "\n"

	if err := os.WriteFile(path, []byte(content), configFilePerm); err != nil {
		return fmt.Errorf("error writing mise config %s: %w", path, err)
	}

	return nil
}
