// Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package mise

import (
	"fmt"
	"os"
	"slices"
	"strings"
)

const (
	// Permission of the generated mise.toml (a config file, not a secret).
	configFilePerm = 0o644

	// AnsiblePythonVersion pins the python (python-build-standalone) mise installs so that
	// `pipx:ansible-core` builds its venv on a self-contained, relocatable interpreter instead of the host
	// python. Owned by furyctl (implementation detail of how ansible is bundled), not by the distribution.
	AnsiblePythonVersion = "3.12"

	// AnsibleUvVersion pins uv, which mise's pipx backend uses to build the ansible venv. Without a
	// managed uv, the backend falls back to a host `pipx`/`uv` that is absent on a clean machine (e.g. a
	// minimal Linux container), breaking the install. Needed only at install time, not at runtime.
	AnsibleUvVersion = "0.9"
)

// Tool describes how a furyctl tool maps to mise.
type Tool struct {
	// Spec is the mise.toml [tools] key (registry shortname or explicit backend).
	Spec string
	// Bin is the executable name, used both for `mise which` and as the materialized symlink name.
	// It is what phase.go / the runners expect under <binPath>/<furyctlName>/<version>/<Bin>.
	Bin string
}

// ManagedTools maps the furyctl tool name (lowercased kfd field) to its mise mapping. Only these are
// managed by mise; awscli/ansible/git stay host dependencies; terraform is kept for backward
// compatibility with distributions that predate opentofu.
//
//nolint:gochecknoglobals // static mapping table.
var ManagedTools = map[string]Tool{
	"kubectl":   {Spec: "kubectl", Bin: "kubectl"},
	"kustomize": {Spec: "kustomize", Bin: "kustomize"},
	"yq":        {Spec: "yq", Bin: "yq"},
	"helm":      {Spec: "helm", Bin: "helm"},
	"helmfile":  {Spec: "helmfile", Bin: "helmfile"},
	"kapp":      {Spec: "kapp", Bin: "kapp"},
	"opentofu":  {Spec: "opentofu", Bin: "tofu"},
	"terraform": {Spec: "aqua:hashicorp/terraform", Bin: "terraform"},
	"furyagent": {Spec: "github:sighupio/furyagent", Bin: "furyagent"},
	// The ansible-core pipx install provides ansible/ansible-playbook/ansible-galaxy. It also needs a
	// python — WriteConfig adds a pinned mise python so the venv is self-contained (see
	// AnsiblePythonVersion). Galaxy collections are installed separately by DownloadTools.
	"ansible": {Spec: "pipx:ansible-core", Bin: "ansible"},
}

// IsManaged reports whether the given furyctl tool is managed by mise.
func IsManaged(name string) bool {
	_, ok := ManagedTools[name]

	return ok
}

// WriteConfig writes a hermetic mise.toml at path with a [tools] section for the given tools
// (furyctl tool name -> version). Keys are always quoted (backends contain ':' and '/'). The ansibleUv
// and ansiblePython args are the distribution-pinned ansible build toolchain; when empty they fall back
// to the built-in defaults.
func WriteConfig(path string, tools map[string]string, ansibleUv, ansiblePython string) error {
	names := make([]string, 0, len(tools))
	for n := range tools {
		names = append(names, n)
	}

	slices.Sort(names)

	lines := []string{"# Generated by furyctl. Do not edit.", "[tools]"}

	// The ansible-core pipx backend needs uv (to build the venv) and a python (so the venv doesn't depend
	// on the host, and so the interpreter lives under mise data for air-gap bundling): pin mise ones so
	// the install is self-contained on a clean machine. The distribution chooses the versions (they track
	// the ansible version); otherwise furyctl's defaults apply.
	if _, ok := tools["ansible"]; ok {
		if ansibleUv == "" {
			ansibleUv = AnsibleUvVersion
		}

		if ansiblePython == "" {
			ansiblePython = AnsiblePythonVersion
		}

		lines = append(lines,
			fmt.Sprintf("%q = %q", "uv", ansibleUv),
			fmt.Sprintf("%q = %q", "python", ansiblePython),
		)
	}

	for _, n := range names {
		t, ok := ManagedTools[n]
		if !ok {
			continue
		}

		lines = append(lines, fmt.Sprintf("%q = %q", t.Spec, tools[n]))
	}

	content := strings.Join(lines, "\n") + "\n"

	if err := os.WriteFile(path, []byte(content), configFilePerm); err != nil {
		return fmt.Errorf("error writing mise config %s: %w", path, err)
	}

	return nil
}
