kind: Bootstrap
metadata:
  name: my-dummy
executor:
  state:
    backend: s3
    config:
      bucket: "im-fury"
      key: "demo"
      region: "eu-milan-1"
provisioner: dummy
spec:

  rsaBits: 4096
