# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

kind: pipeline
name: license

steps:
  - name: check
    image: golang
    pull: always
    commands:
      - go get -u github.com/google/addlicense
      - addlicense -c "SIGHUP s.r.l" -v -l bsd --check .

---
kind: pipeline
name: release

depends_on:
  - license

steps:
  - name: lint
    image: golang
    pull: always
    depends_on:
      - clone
    commands:
      - test -z $(gofmt -l .)
    when:
      event:
        - push
        - tag

  - name: test
    image: golang
    pull: always
    depends_on:
      - clone
    commands:
      - go test -v ./...
    when:
      event:
        - push
        - tag

  - name: build
    image: ghcr.io/goreleaser/goreleaser:v0.149.0
    pull: always
    depends_on:
      - lint
      - test
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - go get -u github.com/gobuffalo/packr/v2/packr2
      - git reset --hard
      - git fetch --tags
      - goreleaser check
      - goreleaser --debug build --skip-validate --rm-dist
    when:
      event:
        - push

  - name: build-release
    image: ghcr.io/goreleaser/goreleaser:v0.149.0
    pull: always
    depends_on:
      - lint
      - test
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - go get -u github.com/gobuffalo/packr/v2/packr2
      - git reset --hard
      - git fetch --tags
      - goreleaser check
      - goreleaser --debug
    when:
      event:
        - tag
