---
kind: pipeline
name: test

workspace:
  base: /go
  path: src/github.com/sighup-io/furyctl

steps:
  - name: lint
    image: golang
    pull: always
    commands:
      - find . -name "*.go" | xargs gofmt -s -d
      # - go vet ./...
    when:
      branch:
      - master
      event:
      - push

  - name: build
    image: golang
    pull: always
    depends_on: 
      - lint
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0    
      version: v0.1.1
    commands:
      - go mod vendor
      - go build -a -ldflags '-extldflags "-static"' -o bin/linux/$(version)/furyctl  .
      - go build -a -ldflags '-extldflags "-static"' -o bin/darwin/$(version)/furyctl .
      - mkdir -p bin/{linux,darwin}/latest
      - cp bin/linux/$(version)/furyctl bin/linux/latest/
      - cp bin/darwin/$(version)/furyctl bin/darwin/latest/
    when:
      branch:
      - master
      event:
      - push
