---
kind: pipeline
name: furyctl

steps:
  - name: lint
    image: golang
    pull: always
    commands:
      - echo ${DRONE_TAG}
      - find . -name "*.go" | xargs gofmt -s -d
      # - go vet ./...
    when:
      event:
        - push
        - tag
      
  - name: build-linux
    group: build
    image: golang
    pull: always
    depends_on: 
      - lint
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - go mod vendor
      - go build -a -ldflags '-extldflags "-static"' -o bin/releases/furyctl-linux-amd64  .
    when:
      event:
        - push
        - tag

  - name: build-darwin
    group: build
    image: golang
    pull: always
    depends_on: 
      - lint
    environment:
      GOOS: darwin
      GOARCH: amd64
      CGO_ENABLED: 0    
    commands:
      - go mod vendor
      - go build -a -ldflags '-extldflags "-static"' -o bin/releases/furyctl-darwin-amd64 .
    when:
      event:
        - push
        - tag

  - name: publish
    image: plugins/github-release
    pull: always
    environment:
    depends_on: 
      - build-linux
      - build-darwin
    settings:
      api_key: 
        from_secret: GITHUB_TOKEN 
      files:
        - bin/releases/*
      checksum:
         - sha256
      title: ${DRONE_TAG}
      #prerelease: true
    when:
      event: tag
