# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

kind: pipeline
type: docker
name: main

node:
  runner: internal

steps:
  - name: check
    image: quay.io/sighup/golang:1.19.0
    pull: always
    commands:
      - go install github.com/google/addlicense@v1.0.0
      - make license-check

  - name: lint
    image: quay.io/sighup/golang:1.19.0
    pull: always
    commands:
      - make lint

  - name: test
    image: quay.io/sighup/golang:1.19.0
    pull: always
    commands:
      - make test
    environment:
      CGO_ENABLED: 0

  - name: build
    image: ghcr.io/goreleaser/goreleaser:v1.11.4
    pull: always
    depends_on:
      - lint
      - test
    environment:
      CGO_ENABLED: 0
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - go install github.com/gobuffalo/packr/v2/packr2@v2.8.3
      - git reset --hard
      - git fetch --tags
      - make build

  - name: integration-template-engine
    image: quay.io/sighup/e2e-furyctl:v1.2.1_v0.2.2_v1.20.1_20.04
    depends_on:
      - build
    environment:
      CGO_ENABLED: 0
      FURYCTL_TOKEN:
        from_secret: FURYCTL_TOKEN
    commands:
      - bats -t ./test/integration/template-engine/tests.sh

  - name: integration-validation-cmd
    image: quay.io/sighup/e2e-furyctl:v1.2.1_v0.2.2_v1.20.1_20.04
    depends_on:
      - build
    environment:
      CGO_ENABLED: 0
      FURYCTL_TOKEN:
        from_secret: FURYCTL_TOKEN
    commands:
      - bats -t ./test/integration/validation-cmd/tests.sh

  - name: e2e-aws
    image: quay.io/sighup/e2e-furyctl:v1.2.1_v0.2.2_v1.20.1_20.04
    pull: always
    privileged: true # Required to connect to the VPN
    depends_on:
      - build
    environment:
      CGO_ENABLED: 0
      FURYCTL_TOKEN:
        from_secret: FURYCTL_TOKEN

      TERRAFORM_TF_STATES_BUCKET_NAME:
        from_secret: TERRAFORM_TF_STATES_BUCKET_NAME
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_REGION:
        from_secret: AWS_REGION
      AWS_DEFAULT_REGION:
        from_secret: AWS_REGION
    commands:
      - bats -t ./test/e2e/aws-eks/tests.sh
    when:
      event:
        - tag

  - name: build-release
    image: ghcr.io/goreleaser/goreleaser:v1.11.4
    pull: always
    depends_on:
      - lint
      - test
      - build
      - integration-aws-eks
      - integration-template-engine
      - integration-validation-cmd
      - e2e-aws
    environment:
      CGO_ENABLED: 0
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - go install github.com/gobuffalo/packr/v2/packr2@v2.8.3
      - git reset --hard
      - git fetch --tags
      - make release
    when:
      ref:
        include:
          - refs/tags/v**

trigger:
  event:
    exclude:
      - pull_request
      - promote
