# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

kind: pipeline
type: docker
name: main

steps:
  - name: prepare
    image: quay.io/sighup/golang:1.19.6
    depends_on:
      - clone
    pull: always
    commands:
      - mkdir -p .go/cache .go/modcache .go/tmp
      - go mod download

  - name: license
    image: quay.io/sighup/golang:1.19.6
    depends_on:
      - clone
    pull: always
    commands:
      - make license-check
    environment:
      CGO_ENABLED: 0
      GOCACHE: /drone/src/.go/cache
      GOMODCACHE: /drone/src/.go/modcache
      GOTMPDIR: /drone/src/.go/tmp

  - name: lint
    image: quay.io/sighup/golang:1.19.6
    depends_on:
      - prepare
    pull: always
    commands:
      - make lint
    environment:
      CGO_ENABLED: 0
      GOCACHE: /drone/src/.go/cache
      GOMODCACHE: /drone/src/.go/modcache
      GOTMPDIR: /drone/src/.go/tmp

  - name: test-unit
    image: quay.io/sighup/golang:1.19.6
    depends_on:
      - prepare
    pull: always
    commands:
      - make test-unit
    environment:
      CGO_ENABLED: 0
      GOCACHE: /drone/src/.go/cache
      GOMODCACHE: /drone/src/.go/modcache
      GOTMPDIR: /drone/src/.go/tmp

  - name: test-integration
    image: quay.io/sighup/golang:1.19.6
    depends_on:
      - prepare
    commands:
      - echo $${NETRC_FILE} > /root/.netrc
      - make test-integration
    environment:
      CGO_ENABLED: 0
      GOCACHE: /drone/src/.go/cache
      GOMODCACHE: /drone/src/.go/modcache
      GOTMPDIR: /drone/src/.go/tmp
      NETRC_FILE:
        from_secret: NETRC_FILE

  - name: test-e2e
    image: quay.io/sighup/golang:1.19.6
    depends_on:
      - prepare
    commands:
      - apk add --update binutils curl groff openssh-client openvpn
      # Install aws-cli
      - curl -sL https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub -o /etc/apk/keys/sgerrand.rsa.pub
      - curl -sLO https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$${GLIBC_VER}/glibc-$${GLIBC_VER}.apk
      - curl -sLO https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$${GLIBC_VER}/glibc-bin-$${GLIBC_VER}.apk
      - curl -sLO https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$${GLIBC_VER}/glibc-i18n-$${GLIBC_VER}.apk
      - apk add --force-overwrite --virtual .glibc glibc-$${GLIBC_VER}.apk glibc-bin-$${GLIBC_VER}.apk glibc-i18n-$${GLIBC_VER}.apk
      - /usr/glibc-compat/bin/localedef -i en_US -f UTF-8 en_US.UTF-8
      - curl -sL https://awscli.amazonaws.com/awscli-exe-linux-x86_64-$${AWSCLI_VERSION}.zip -o awscliv2.zip
      - unzip awscliv2.zip
      - aws/install
      - apk add gcompat || true
      # Setup SSH
      - mkdir /root/.ssh
      - echo "$${GITHUB_SSH}" | tr -d '\r' | sed -e '$a\' > /root/.ssh/id_rsa
      - echo $${NETRC_FILE} > /root/.netrc
      - chmod 600 /root/.ssh/id_rsa
      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null
      # Create required s3 bucket if it doesn't exist
      - (test ! $(aws s3api get-bucket-location --bucket furyctl-e2e-deps-test --output text --no-cli-pager 2>/dev/null | grep "$${AWS_DEFAULT_REGION}")) && aws s3 mb s3://furyctl-e2e-deps-test --region $${AWS_DEFAULT_REGION}
      # Run tests
      - make test-e2e
    environment:
      CGO_ENABLED: 0
      GOCACHE: /drone/src/.go/cache
      GOMODCACHE: /drone/src/.go/modcache
      GOTMPDIR: /drone/src/.go/tmp
      AWSCLI_VERSION: 2.8.12
      GLIBC_VER: 2.35-r0
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION:
        from_secret: AWS_REGION
      FURYCTL_MIXPANEL_TOKEN:
        from_secret: FURYCTL_MIXPANEL_TOKEN
      NETRC_FILE:
        from_secret: NETRC_FILE
      GITHUB_SSH:
        from_secret: GITHUB_SSH

  - name: build
    image: ghcr.io/goreleaser/goreleaser:v1.15.2
    depends_on:
      - prepare
    pull: always
    commands:
      - git reset --hard
      - git fetch --tags
      - make build
    when:
      ref:
        exclude:
          - refs/tags/v**
    environment:
      CGO_ENABLED: 0
      GOCACHE: /drone/src/.go/cache
      GOMODCACHE: /drone/src/.go/modcache
      GOTMPDIR: /drone/src/.go/tmp
      FURYCTL_MIXPANEL_TOKEN:
        from_secret: FURYCTL_MIXPANEL_TOKEN
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN

  - name: build-release
    image: ghcr.io/goreleaser/goreleaser:v1.15.2
    pull: always
    depends_on:
      - lint
      - test-unit
      - test-integration
    commands:
      - git reset --hard
      - git fetch --tags
      - make release
    when:
      ref:
        include:
          - refs/tags/v**
    environment:
      CGO_ENABLED: 0
      GOCACHE: /drone/src/.go/cache
      GOMODCACHE: /drone/src/.go/modcache
      GOTMPDIR: /drone/src/.go/tmp
      FURYCTL_MIXPANEL_TOKEN:
        from_secret: FURYCTL_MIXPANEL_TOKEN
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN

trigger:
  event:
    exclude:
      - pull_request
      - promote
