---
kind: pipeline
name: test

steps:
  - name: lint
    image: golang
    pull: always
    commands:
      - find . -name "*.go" | xargs gofmt -s -d
      # - go vet ./...

  - name: build-linux
    group: build
    image: golang
    pull: always
    depends_on: 
      - lint
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0    
      VERSION: v0.1.1b #FIXME
    commands:
      - go mod vendor
      - go build -a -ldflags '-extldflags "-static"' -o bin/linux/$VERSION/furyctl  .
      - mkdir -p bin/linux/latest
      - cp bin/linux/$VERSION/furyctl bin/linux/latest/furyctl-linux-amd64

  - name: build-darwin
    group: build
    image: golang
    pull: always
    depends_on: 
      - lint
    environment:
      GOOS: darwin
      GOARCH: amd64
      CGO_ENABLED: 0    
      VERSION: v0.1.1b #FIXME
    commands:
      - go mod vendor
      - go build -a -ldflags '-extldflags "-static"' -o bin/darwin/$VERSION/furyctl .
      - mkdir -p bin/darwin/latest
      - cp bin/darwin/$VERSION/furyctl bin/darwin/latest/furyctl-darwin-amd64

  - name: publish
    image: plugins/github-release
    pull: always
    depends_on: 
      - build-linux
      - build-darwin
    settings:
      api_key:
        from_secret: github_token
      files:
        - bin/darwin/latest
        - bin/linux/latest
    title: 0.1.1b #FIXME
    note: CHANGELOG.md
    prerelease: true
    when:
      branch:
        - master
      event:
        - push #CHANGEME

trigger:
  branch:
  - master
