# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

kind: pipeline
type: docker
name: main

steps:
  - name: prepare
    image: quay.io/sighup/golang:1.19.1
    depends_on:
      - clone
    pull: always
    commands:
      - mkdir -p .go/cache .go/modcache .go/tmp
      - go mod download

  - name: license
    image: quay.io/sighup/golang:1.19.1
    depends_on:
      - clone
    pull: always
    commands:
      - go install github.com/google/addlicense@v1.0.0
      - make license-check
    environment:
      CGO_ENABLED: 0
      GOCACHE: /drone/src/.go/cache
      GOMODCACHE: /drone/src/.go/modcache
      GOTMPDIR: /drone/src/.go/tmp

  - name: lint
    image: quay.io/sighup/golang:1.19.1
    depends_on:
      - prepare
    pull: always
    commands:
      - make lint
    environment:
      CGO_ENABLED: 0
      GOCACHE: /drone/src/.go/cache
      GOMODCACHE: /drone/src/.go/modcache
      GOTMPDIR: /drone/src/.go/tmp

  - name: test-unit
    image: quay.io/sighup/golang:1.19.1
    depends_on:
      - prepare
    pull: always
    commands:
      - make test-unit
    environment:
      CGO_ENABLED: 0
      GOCACHE: /drone/src/.go/cache
      GOMODCACHE: /drone/src/.go/modcache
      GOTMPDIR: /drone/src/.go/tmp

  - name: test-integration
    image: quay.io/sighup/golang:1.19.1
    depends_on:
      - prepare
    commands:
      - make test-integration
    environment:
      CGO_ENABLED: 0
      GOCACHE: /drone/src/.go/cache
      GOMODCACHE: /drone/src/.go/modcache
      GOTMPDIR: /drone/src/.go/tmp
      NETRC_FILE:
        from_secret: NETRC_FILE

  - name: test-e2e
    image: quay.io/sighup/golang:1.19.1
    depends_on:
      - prepare
    commands:
      - make test-e2e
    environment:
      CGO_ENABLED: 0
      GOCACHE: /drone/src/.go/cache
      GOMODCACHE: /drone/src/.go/modcache
      GOTMPDIR: /drone/src/.go/tmp
      NETRC_FILE:
        from_secret: NETRC_FILE

  - name: build
    image: ghcr.io/goreleaser/goreleaser:v1.11.4
    depends_on:
      - prepare
    pull: always
    commands:
      - go install github.com/gobuffalo/packr/v2/packr2@v2.8.3
      - git reset --hard
      - git fetch --tags
      - make build
    when:
      ref:
        exclude:
          - refs/tags/v**
    environment:
      CGO_ENABLED: 0
      GOCACHE: /drone/src/.go/cache
      GOMODCACHE: /drone/src/.go/modcache
      GOTMPDIR: /drone/src/.go/tmp
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN

  - name: build-release
    image: ghcr.io/goreleaser/goreleaser:v1.11.4
    pull: always
    depends_on:
      - lint
      - test-unit
      - test-integration
    commands:
      - go install github.com/gobuffalo/packr/v2/packr2@v2.8.3
      - git reset --hard
      - git fetch --tags
      - make release
    when:
      ref:
        include:
          - refs/tags/v**
    environment:
      CGO_ENABLED: 0
      GOCACHE: /drone/src/.go/cache
      GOMODCACHE: /drone/src/.go/modcache
      GOTMPDIR: /drone/src/.go/tmp
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN

trigger:
  event:
    exclude:
      - pull_request
      - promote
