---
kind: pipeline
name: test

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: lint
    image: golang
    pull: always
    depends_on:
      - fetch
    commands:
      - find . -name "*.go" | xargs gofmt -s -d
      #- go vet ./...
    when:
      event:
        - push
        - tag

  - name: go-mod-vendor
    image: golang
    pull: always
    depends_on:
      - lint
    commands:
      - go mod vendor
    when:
      event:
        - push

  - name: build-linux-push
    group: build
    image: golang
    pull: always
    depends_on:
      - go-mod-vendor
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - go build
    when:
      event:
        - push

  - name: build-darwin-push
    group: build
    image: golang
    pull: always
    depends_on:
      - go-mod-vendor
    environment:
      GOOS: darwin
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - go build
    when:
      event:
        - push

  - name: build-release
    image: goreleaser/goreleaser:v0.124
    pull: always
    depends_on:
      - lint
      - fetch
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    secrets:
      - GITHUB_TOKEN
    commands:
      - goreleaser check
      - goreleaser --debug
    when:
      event:
        - tag
