---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: lint
    image: golang
    pull: always
    depends_on: [ clone ]
    commands:
      - find . -name "*.go" | xargs gofmt -s -d
      - find . -name "*.go" | xargs go vet
    when:
      event:
      - push

  - name: build
    image: golang
    pull: always
    depends_on: [ lint ]
    commands:
      -	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-extldflags "-static"' -o bin/linux/$(version)/furyctl  .
      - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -a -ldflags '-extldflags "-static"' -o bin/darwin/$(version)/furyctl .
    when:
      event:
      - push


