---
before:
  hooks:
    - go mod vendor
project_name: furyctl
builds:
  - binary: 'furyctl'
    id: furyctl-darwin
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/sighupio/furyctl/cmd.version={{.Version}} -X github.com/sighupio/furyctl/cmd.commit={{.Commit}} -X github.com/sighupio/furyctl/cmd.date={{.Date}}
  - binary: 'furyctl'
    id: furyctl-linux
    goarch:
      - amd64
    goos:
      - linux
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/sighupio/furyctl/cmd.version={{.Version}} -X github.com/sighupio/furyctl/cmd.commit={{.Commit}} -X github.com/sighupio/furyctl/cmd.date={{.Date}}
archives:
  - format: tar.gz
    id: furyctl-darwin-tgz
    wrap_in_directory: false
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - furyctl-darwin
  - format: tar.gz
    id: furyctl-linux-tgz
    wrap_in_directory: false
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - furyctl-linux
  - format: binary
    id: furyctl-darwin-bin
    wrap_in_directory: false
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - furyctl-darwin
  - format: binary
    id: furyctl-linux-bin
    wrap_in_directory: false
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - furyctl-linux
checksum:
  name_template: 'sha256sum.txt'
snapshot:
  name_template: '{{ .Tag }}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  ids:
    - furyctl-linux-tgz
    - furyctl-linux-bin
    - furyctl-darwin-tgz
    - furyctl-darwin-bin
  github:
    owner: sighupio
    name: furyctl
  name_template: '{{ .Tag }}'
brews:
  - name: furyctl
    tap:
      owner: sighupio
      name: homebrew-furyctl
    folder: Formula
    homepage: 'https://gihub.com/sighupio/furyctl'
    description: 'Furyctl  binary'
    conflicts:
      - furyctl
    test: |
      system "#{bin}/furyctl"
    install: |
      bin.install 'furyctl'
