# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
before:
  hooks:
    - packr2 build
project_name: furyctl
builds:
  - binary: 'furyctl'
    id: furyctl-darwin
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/sighupio/furyctl/cmd.version={{.Version}} -X github.com/sighupio/furyctl/cmd.commit={{.Commit}} -X github.com/sighupio/furyctl/cmd.date={{.Date}}
  - binary: 'furyctl'
    id: furyctl-linux
    goarch:
      - amd64
      - arm64
    goos:
      - linux
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/sighupio/furyctl/cmd.version={{.Version}} -X github.com/sighupio/furyctl/cmd.commit={{.Commit}} -X github.com/sighupio/furyctl/cmd.date={{.Date}}
archives:
  - format: tar.gz
    id: furyctl-darwin-tgz
    wrap_in_directory: false
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - furyctl-darwin
  - format: tar.gz
    id: furyctl-linux-tgz
    wrap_in_directory: false
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - furyctl-linux
  - format: binary
    id: furyctl-darwin-bin
    wrap_in_directory: false
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - furyctl-darwin
  - format: binary
    id: furyctl-linux-bin
    wrap_in_directory: false
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - furyctl-linux
checksum:
  name_template: 'sha256sum.txt'
snapshot:
  name_template: '{{ .Tag }}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  ids:
    - furyctl-linux-tgz
    - furyctl-linux-bin
    - furyctl-darwin-tgz
    - furyctl-darwin-bin
  github:
    owner: sighupio
    name: furyctl
  name_template: '{{ .Tag }}'
