# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
project_name: furyctl
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.gitCommit={{.Commit}} -X main.buildTime={{.Date}} -X main.goVersion={{.Env.GO_VERSION}} -X main.osArch={{.Arch}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: sighupio
    name: furyctl
  name_template: '{{ .Tag }}'
  prerelease: auto
brews:
  - name: furyctl
    tap:
      owner: sighupio
      name: homebrew-furyctl
    skip_upload: auto
    folder: Formula
    homepage: 'https://gihub.com/sighupio/furyctl'
    description: 'Furyctl binary'
    conflicts:
      - furyctl
    test: |
      system "#{bin}/furyctl"
    install: |
      bin.install 'furyctl'
