# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.3.2/www/docs/static/schema.json

# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

version: 2
project_name: furyctl
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
      - MIX_PANEL_TOKEN={{ if index .Env "FURYCTL_MIXPANEL_TOKEN" }}{{ .Env.FURYCTL_MIXPANEL_TOKEN }}{{ else }}""{{ end }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.gitCommit={{.Commit}}
      - -X main.buildTime={{.Date}}
      - -X main.goVersion={{.Env.GO_VERSION}}
      - -X main.osArch={{.Arch}}
      - -X main.mixPanelToken={{.Env.MIX_PANEL_TOKEN}}
archives:
  - name_template: "{{ tolower .ProjectName }}-{{ tolower .Os }}-{{ tolower .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-develop"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: sighupio
    name: furyctl
  name_template: "{{ .Tag }}"
  prerelease: auto
brews:
  - name: furyctl
    repository:
      owner: sighupio
      name: homebrew-furyctl
    skip_upload: auto
    directory: Formula
    homepage: "https://gihub.com/sighupio/furyctl"
    description: "furyctl binary"
    conflicts:
      - furyctl
    test: |
      system "#{bin}/furyctl"
    install: |
      bin.install 'furyctl'
