// Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build unit

package create //nolint:testpackage // exercises unexported version-resolution helpers.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Mirrors distribution/templates/kubernetes/immutable/group_vars/all.yml.tpl so the test exercises the
// real rendering path without depending on a distribution checkout.
const versionVarsTestTemplate = `---
# Generated by furyctl from immutable.yaml — DO NOT EDIT.
kubernetes_version: {{ .versions.kubernetes_version }}
kubernetes_image_registry: {{ .versions.kubernetes_image_registry }}
containerd_sandbox_image: {{ .versions.containerd_sandbox_image }}
coredns_image_prefix: {{ .versions.coredns_image_prefix }}
os_update_target_version: {{ .versions.os_update_target_version }}
{{- if .versions.kubectl_bin }}
kubectl_bin: {{ .versions.kubectl_bin }}
{{- end }}
sysext_targets:
{{- range $name, $t := .versions.sysext_targets }}
  {{ $name }}:
    version: {{ $t.version }}
    arch:
{{- range $arch, $a := $t.arch }}
      {{ $arch }}:
        url: {{ $a.url }}
{{- end }}
{{- end }}
`

func TestNormalizeVersion(t *testing.T) {
	t.Parallel()

	cases := map[string]string{
		"v1.34.8": "1.34.8",
		"1.34.8":  "1.34.8",
		"v1.35.5": "1.35.5",
		"":        "",
	}

	for in, want := range cases {
		if got := normalizeVersion(in); got != want {
			t.Errorf("normalizeVersion(%q) = %q, want %q", in, got, want)
		}
	}
}

const testManifest = `---
kubernetes:
  1.34.8:
    imageRegistry: registry.sighup.io/fury/on-premises
    sandboxImage: registry.sighup.io/fury/on-premises/pause:3.10.1
    corednsImagePrefix: /coredns
    sysext:
      - name: containerd
        version: 2.3.1
        arch:
          x86-64:
            url: https://example/containerd-2.3.1-x86-64.raw
      - name: kubernetes
        version: v1.34.8
        arch:
          x86-64:
            url: https://example/kubernetes-v1.34.8-x86-64.raw
    flatcar:
      version: 4593.2.1
      channel: stable
      arch:
        x86-64:
          kernel:
            filename: k
            url: https://example/k
`

// writeManifest lays out a phase dir with a sibling vendor/installers/immutable/immutable.yaml.
func writeManifest(t *testing.T) string {
	t.Helper()

	base := t.TempDir()
	phaseDir := filepath.Join(base, "kubernetes")
	manifestDir := filepath.Join(base, "vendor", "installers", "immutable")

	if err := os.MkdirAll(phaseDir, 0o755); err != nil {
		t.Fatal(err)
	}

	if err := os.MkdirAll(manifestDir, 0o755); err != nil {
		t.Fatal(err)
	}

	if err := os.WriteFile(filepath.Join(manifestDir, "immutable.yaml"), []byte(testManifest), 0o600); err != nil {
		t.Fatal(err)
	}

	return phaseDir
}

func TestSelectImmutableAssets(t *testing.T) {
	t.Parallel()

	phaseDir := writeManifest(t)

	// Selects by the normalized kubernetes version from kfd.immutable.version (leading v stripped).
	got, err := selectImmutableAssets(phaseDir, "v1.34.8")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if got.SandboxImage != "registry.sighup.io/fury/on-premises/pause:3.10.1" {
		t.Errorf("SandboxImage = %q", got.SandboxImage)
	}

	if got.ImageRegistry != "registry.sighup.io/fury/on-premises" {
		t.Errorf("ImageRegistry = %q", got.ImageRegistry)
	}

	if got.CorednsImagePrefix != "/coredns" {
		t.Errorf("CorednsImagePrefix = %q", got.CorednsImagePrefix)
	}

	// A version absent from the manifest is an error.
	if _, err := selectImmutableAssets(phaseDir, "v9.99.99"); err == nil {
		t.Error("expected error for missing version, got nil")
	}
}

func TestRenderVersionVarsFileIsDeterministic(t *testing.T) {
	t.Parallel()

	phaseDir := writeManifest(t)

	a, err := selectImmutableAssets(phaseDir, "1.34.8")
	if err != nil {
		t.Fatal(err)
	}

	// The same selected block must render byte-identical vars — this is the guarantee
	// that apply and the upgrade playbooks receive the same version vars file.
	dirA := t.TempDir()
	dirB := t.TempDir()

	tplPath := filepath.Join(t.TempDir(), "all.yml.tpl")
	if err := os.WriteFile(tplPath, []byte(versionVarsTestTemplate), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := renderVersionVarsFile(dirA, "1.34.8", "/usr/bin/kubectl", tplPath, a); err != nil {
		t.Fatal(err)
	}

	if err := renderVersionVarsFile(dirB, "1.34.8", "/usr/bin/kubectl", tplPath, a); err != nil {
		t.Fatal(err)
	}

	outA, err := os.ReadFile(filepath.Join(dirA, "group_vars", "all.yml"))
	if err != nil {
		t.Fatal(err)
	}

	outB, err := os.ReadFile(filepath.Join(dirB, "group_vars", "all.yml"))
	if err != nil {
		t.Fatal(err)
	}

	if string(outA) != string(outB) {
		t.Errorf("rendered vars files differ:\nA:\n%s\nB:\n%s", outA, outB)
	}

	// The rendered file must carry every version-dependent variable the roles consume.
	for _, key := range []string{
		"kubernetes_version: 1.34.8",
		"containerd_sandbox_image: registry.sighup.io/fury/on-premises/pause:3.10.1",
		"coredns_image_prefix: /coredns",
		"kubernetes_image_registry: registry.sighup.io/fury/on-premises",
		"os_update_target_version:",
		"sysext_targets:",
		"version: 2.3.1",
		"url: https://example/containerd-2.3.1-x86-64.raw",
		"kubectl_bin: /usr/bin/kubectl",
	} {
		if !strings.Contains(string(outA), key) {
			t.Errorf("rendered vars file missing %q:\n%s", key, outA)
		}
	}
}
