
---
apiVersion: kfd.sighup.io/v1alpha2
kind: EKSCluster
metadata:
  name: example
spec:
  distributionVersion: v1.25.2
  toolsConfiguration:
    terraform:
      state:
        s3:
          bucketName: example
          keyPrefix: test/example
          region: eu-west-1
  region: eu-west-1
  tags:
    env: "test"
    k8s: "example"
    githubOrg: "acme"
    githubRepo: "furyctl"
  infrastructure:
    vpc:
      network:
        cidr: 10.10.0.0/16
        subnetsCidrs:
          private:
            - 10.10.0.0/20
            - 10.10.16.0/20
            - 10.10.32.0/20
            - 10.10.48.0/20
          public:
            - 10.10.192.0/24
            - 10.10.193.0/24
            - 10.10.194.0/24
    vpn:
      instances: 1
      instanceType: t3.micro
      diskSize: 50
      operatorName: acme
      dhParamsBits: 2048
      vpnClientsSubnetCidr: 172.16.0.0/16
      ssh:
        publicKeys: ["{file:///<HOME>/.ssh/id_rsa.pub}"]
        githubUsersName:
          - <USER>
        allowedFromCidrs:
          - 0.0.0.0/0
  kubernetes:
    apiServer:
      privateAccess: true
      publicAccess: false
      privateAccessCidrs: ["0.0.0.0/0"]
      publicAccessCidrs: []
    nodeAllowedSshPublicKey: "{file:///<HOME>/.ssh/id_rsa.pub}"
    nodePoolsLaunchKind: "launch_templates"
    logRetentionDays: 1
    nodePools:
      - name: infra
        size:
          min: 3
          max: 3
        instance:
          type: t3.xlarge
          spot: true
          volumeSize: 50
        labels:
          nodepool: infra
          node.kubernetes.io/role: infra
        taints:
          - node.kubernetes.io/role=infra:NoSchedule
        tags:
          k8s.io/cluster-autoscaler/node-template/label/nodepool: "infra"
          k8s.io/cluster-autoscaler/node-template/label/node.kubernetes.io/role: "infra"
          k8s.io/cluster-autoscaler/node-template/taint/node.kubernetes.io/role: "infra:NoSchedule"
  distribution:
    modules:
      ingress:
        baseDomain: internal.example.dev
        nginx:
          type: dual
          tls:
            provider: certManager
        certManager:
          clusterIssuer:
            name: letsencrypt-fury
            email: fury@example.dev
            type: http01
        dns:
          public:
            name: "example.dev"
            create: true
          private:
            name: "internal.example.dev"
            create: true
      logging:
        type: loki
      dr:
        velero:
          eks:
            bucketName: furyctl-example-qgcurpen
            region: eu-west-1
