// Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package clusterpki

import (
	"crypto"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math"
	"math/big"
	"time"

	certutil "k8s.io/client-go/util/cert"
)

// These mirror kubeadm's defaults for a CA generated with an empty
// EncryptionAlgorithm, which is what furyctl always asked it for.
const (
	caKeyBits   = 2048
	caValidity  = 10 * 365 * 24 * time.Hour
	certPEMType = "CERTIFICATE"
)

// NewCertificateAuthority creates a self-signed CA certificate and its private key.
//
// It replaces kubeadm's pkiutil.NewCertificateAuthority. The certificate it
// produces is interchangeable with kubeadm's, so keep the quirks below (the CN
// repeated as a SAN, the serial range, the 10 year validity) rather than
// "correcting" them: existing PKI folders were generated by kubeadm.
func NewCertificateAuthority(cfg *certutil.Config) (*x509.Certificate, crypto.Signer, error) {
	key, err := rsa.GenerateKey(rand.Reader, caKeyBits)
	if err != nil {
		return nil, nil, fmt.Errorf("error while generating CA private key: %w", err)
	}

	cert, err := newSelfSignedCACert(cfg, key)
	if err != nil {
		return nil, nil, err
	}

	return cert, key, nil
}

func newSelfSignedCACert(cfg *certutil.Config, key crypto.Signer) (*x509.Certificate, error) {
	// A uniform random value in [1, MaxInt64), as kubeadm does it.
	serial, err := rand.Int(rand.Reader, big.NewInt(math.MaxInt64-1))
	if err != nil {
		return nil, fmt.Errorf("error while generating certificate serial number: %w", err)
	}

	serial.Add(serial, big.NewInt(1))

	notBefore := time.Now().UTC()
	if !cfg.NotBefore.IsZero() {
		notBefore = cfg.NotBefore
	}

	tmpl := x509.Certificate{
		SerialNumber: serial,
		Subject: pkix.Name{
			CommonName:   cfg.CommonName,
			Organization: cfg.Organization,
		},
		NotBefore:             notBefore,
		NotAfter:              notBefore.Add(caValidity),
		KeyUsage:              x509.KeyUsageKeyEncipherment | x509.KeyUsageDigitalSignature | x509.KeyUsageCertSign,
		BasicConstraintsValid: true,
		IsCA:                  true,
	}

	if cfg.CommonName != "" {
		tmpl.DNSNames = []string{cfg.CommonName}
	}

	der, err := x509.CreateCertificate(rand.Reader, &tmpl, &tmpl, key.Public(), key)
	if err != nil {
		return nil, fmt.Errorf("error while creating self-signed CA certificate: %w", err)
	}

	cert, err := x509.ParseCertificate(der)
	if err != nil {
		return nil, fmt.Errorf("error while parsing the generated CA certificate: %w", err)
	}

	return cert, nil
}

// EncodeCertPEM returns the PEM encoding of cert.
func EncodeCertPEM(cert *x509.Certificate) []byte {
	return pem.EncodeToMemory(&pem.Block{Type: certPEMType, Bytes: cert.Raw})
}
